### ISSUE TITLE
Documentation support with GraphiQL

### ISSUE THREAD

**Issue by Seluj78** [yfilali/graphql-pynamodb#13]
See https://github.com/graphql-python/flask-graphql/issues/44

How would one document his graphiql mutations etc ?

**Comment by yfilali** [comment]
At the moment, only the attribute name is automatically provided as the "doc" for graphiql. This is because the automatic conversion from PynamoDB types to graphene types has no other attributes on the PynamoDB Attribute class to pull a full description from.

The long way around this is to create fields manually on your GraphQL models with a source='field_name' and a description="Doc goes here":

```
class MyType(PynamoObjectType):
    my_field = String(source='my_field', description='This is a long description of field_name')
    class Meta:
        model = MyDBType
```

**Comment by Seluj78** [comment]
Alright, thanks for the reply ! I'll close this then, and keep it for future reference ! Cheers and thanks for the work !
